# Generated by Django 3.1.2 on 2020-11-24 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20201117_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='views',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='views',
            new_name='rating',
        ),
    ]
