# Generated by Django 3.1.2 on 2020-12-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20201130_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='question',
            name='rating',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Рейтинг'),
        ),
    ]
