# Generated by Django 3.1.2 on 2020-11-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201115_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/img/default.png', upload_to='static/img/'),
        ),
    ]
