# Generated by Django 3.1.2 on 2020-11-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201117_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='comments', to='app.Profile', verbose_name='Лайки пользователей'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, to='app.Tag', verbose_name='Теги'),
        ),
    ]
