# Generated by Django 3.1.2 on 2020-11-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201117_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='questions',
            field=models.ManyToManyField(blank=True, default=None, to='app.Question', verbose_name='Вопросы'),
        ),
    ]
