# Generated by Django 3.1.2 on 2020-11-17 19:25

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201117_1528'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='active_status',
            field=models.BooleanField(default=True, verbose_name='Статус активности'),
        ),
        migrations.AddField(
            model_name='question',
            name='answers_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество ответов'),
        ),
        migrations.AddField(
            model_name='question',
            name='views',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.profile'),
        ),
    ]
