# Generated by Django 3.1.2 on 2020-11-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201117_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='views',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Количество просмотров'),
        ),
    ]
